#!/usr/bin/env python3
"""Reproducible offline audit of the 2026-07-09 salvage first-light data.

The script never edits raw FITS.  It writes provisional products beneath a
``generated/`` directory: header/sequence inventories, detector calibration
frames, a conservative bad-pixel mask, representative corrected images, and a
machine-readable metrics file.  Results are commissioning diagnostics, not
calibrated sky polarization.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import sys
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from astropy.io import fits
from astropy.stats import sigma_clipped_stats
from scipy.ndimage import binary_dilation, gaussian_filter, maximum_filter

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import caltools as ct  # noqa: E402


HEADER_KEYS = (
    "DATE-OBS", "TIMESYS", "TIME-SRC", "TIMEUNC", "EXPTIME", "IMAGETYP",
    "OBJECT", "FILTER", "GAIN", "EGAIN", "OFFSET", "READMODE", "RMODE",
    "DET-TEMP", "CCD-TEMP", "SET-TEMP", "HWPANG", "POLSEQ", "POLSEQN", "INSTROT",
    "PIXSCALE", "RA", "DEC", "AIRMASS",
)


def _jsonable(value: Any) -> Any:
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (np.floating,)):
        return float(value)
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, Path):
        return str(value)
    return value


def _robust(values: np.ndarray) -> dict[str, float]:
    values = np.asarray(values, dtype=np.float64)
    values = values[np.isfinite(values)]
    mean, median, std = sigma_clipped_stats(
        values, sigma=5.0, maxiters=5
    )
    mad = 1.4826 * np.median(np.abs(values - np.median(values)))
    return {
        "mean": float(mean),
        "median": float(median),
        "std": float(std),
        "mad_sigma": float(mad),
        "minimum": float(np.min(values)),
        "maximum": float(np.max(values)),
    }


def _valid_session_date(value: Any, year: int = 2026) -> bool:
    if not value:
        return False
    try:
        return datetime.fromisoformat(str(value).replace("Z", "+00:00")).year == year
    except ValueError:
        return False


def _inventory(paths: list[Path]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for path in paths:
        hdr = fits.getheader(path, ignore_missing_end=True)
        row = {"filename": path.name}
        row.update({key: hdr.get(key) for key in HEADER_KEYS})
        row["date_obs_valid_2026"] = _valid_session_date(hdr.get("DATE-OBS"))
        rows.append(row)
    return rows


def _write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    if not rows:
        return
    fieldnames = list(rows[0])
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def _paths_matching(rows: list[dict[str, Any]], directory: Path, **wanted) -> list[str]:
    return [
        str(directory / row["filename"])
        for row in rows
        if all(row.get(key) == value for key, value in wanted.items())
    ]


def _write_image(path: Path, data: np.ndarray, label: str, unit: str) -> None:
    header = fits.Header()
    header["BUNIT"] = unit
    header["HISTORY"] = "Generated by scripts/analyze_salvage_first_light.py"
    header["COMMENT"] = label
    fits.PrimaryHDU(np.asarray(data), header=header).writeto(path, overwrite=True)


def _outlier_mask(data: np.ndarray, nsigma: float = 10.0) -> np.ndarray:
    values = np.asarray(data, dtype=np.float64)
    med = float(np.nanmedian(values))
    mad = float(1.4826 * np.nanmedian(np.abs(values - med)))
    if not np.isfinite(mad) or mad <= 0:
        mad = float(np.nanstd(values))
    return ~np.isfinite(values) | (np.abs(values - med) > nsigma * mad)


def _representative_paths(rows: list[dict[str, Any]], directory: Path) -> list[Path]:
    selected: dict[tuple[str, float], Path] = {}
    for row in rows:
        if row.get("IMAGETYP") != "LIGHT" or not row.get("POLSEQ"):
            continue
        key = (str(row["POLSEQ"]), float(row["HWPANG"]))
        selected.setdefault(key, directory / row["filename"])
    return [selected[key] for key in sorted(selected)]


def _candidate_peaks(
    corrected: np.ndarray,
    bad_mask: np.ndarray,
    sigma_px: float = 2.0,
) -> tuple[list[dict[str, float]], np.ndarray, np.ndarray]:
    expanded_bad = binary_dilation(bad_mask, iterations=5)
    work = np.array(corrected, dtype=np.float32, copy=True)
    fill = float(np.median(work[~expanded_bad]))
    work[expanded_bad] = fill
    smooth = gaussian_filter(work, sigma=sigma_px)
    stats = _robust(smooth[~expanded_bad])
    noise = max(stats["mad_sigma"], stats["std"], 1e-6)
    threshold = stats["median"] + 8.0 * noise
    maxima = smooth == maximum_filter(smooth, size=11, mode="nearest")
    yy, xx = np.nonzero(maxima & ~expanded_bad & (smooth > threshold))
    snr = (smooth[yy, xx] - stats["median"]) / noise
    order = np.argsort(snr)[::-1][:250]
    peaks = [
        {"x": float(xx[i]), "y": float(yy[i]), "smooth_snr": float(snr[i])}
        for i in order
    ]
    return peaks, smooth, expanded_bad


def _nominal_vertical_pairs(
    peaks: list[dict[str, float]], separation_px: float = 60.0, tolerance_px: float = 4.0
) -> list[dict[str, float]]:
    pairs: list[dict[str, float]] = []
    for i, first in enumerate(peaks):
        for second in peaks[i + 1:]:
            dx = second["x"] - first["x"]
            dy = second["y"] - first["y"]
            if abs(dx) <= tolerance_px and abs(abs(dy) - separation_px) <= tolerance_px:
                pairs.append({
                    "x1": first["x"], "y1": first["y"],
                    "x2": second["x"], "y2": second["y"],
                    "separation_px": float(math.hypot(dx, dy)),
                    "minimum_snr": min(first["smooth_snr"], second["smooth_snr"]),
                })
    return sorted(pairs, key=lambda item: item["minimum_snr"], reverse=True)


def _block_mean(data: np.ndarray, bad: np.ndarray, factor: int = 8) -> np.ndarray:
    ny = (data.shape[0] // factor) * factor
    nx = (data.shape[1] // factor) * factor
    work = np.asarray(data[:ny, :nx], dtype=np.float32).copy()
    work[bad[:ny, :nx]] = np.nan
    blocks = work.reshape(ny // factor, factor, nx // factor, factor)
    with np.errstate(invalid="ignore"):
        return np.nanmean(blocks, axis=(1, 3))


def _plot_representatives(
    output: Path,
    images: list[tuple[str, np.ndarray]],
    bad_mask: np.ndarray,
) -> None:
    fig, axes = plt.subplots(2, 2, figsize=(14, 10), constrained_layout=True)
    for ax, (label, image) in zip(axes.flat, images):
        small = _block_mean(image, bad_mask, factor=8)
        stats = _robust(small)
        span = max(4.0 * stats["std"], 1.0)
        im = ax.imshow(
            small,
            origin="upper",
            cmap="gray",
            vmin=stats["median"] - span,
            vmax=stats["median"] + span,
            interpolation="nearest",
        )
        ax.set_title(label)
        ax.set_xlabel("X / 8 [binned detector pixels]")
        ax.set_ylabel("Y / 8 [binned detector pixels]")
        fig.colorbar(im, ax=ax, shrink=0.75, label="bias+dark-subtracted ADU")
    fig.suptitle("2026-07-09 salvage first light: representative corrected frames")
    fig.savefig(output / "representative_corrected_frames.png", dpi=160)
    plt.close(fig)


def _superflat_roi_metrics(
    rows: list[dict[str, Any]],
    directory: Path,
    master_bias: np.ndarray,
    master_dark: np.ndarray,
    bad_mask: np.ndarray,
) -> list[dict[str, Any]]:
    roi = (slice(1600, 2600), slice(2100, 4100))
    bias_roi = master_bias[roi]
    dark_roi = master_dark[roi]
    good_roi = ~bad_mask[roi]
    by_angle: dict[float, list[str]] = defaultdict(list)
    for row in rows:
        if row.get("POLSEQ") == "superflatV_drift":
            by_angle[float(row["HWPANG"])].append(str(directory / row["filename"]))

    metrics: list[dict[str, Any]] = []
    for angle, paths in sorted(by_angle.items()):
        cube = ct.load_cube(paths, roi=roi)
        calibrated = cube - bias_roi[np.newaxis] - dark_roi[np.newaxis]
        combined = np.median(calibrated, axis=0)
        stats = _robust(combined[good_roi])
        metrics.append({
            "hwp_angle_deg": angle,
            "n_frames": len(paths),
            **{f"combined_{key}_adu": value for key, value in stats.items()},
            "single_frame_median_adu": float(np.median(calibrated[:, good_roi])),
        })
        del cube, calibrated, combined
    return metrics


def analyze(session_dir: Path, output: Path) -> dict[str, Any]:
    output.mkdir(parents=True, exist_ok=True)
    fits_paths = sorted(session_dir.glob("*.fits"))
    if not fits_paths:
        raise FileNotFoundError(f"No .fits files in {session_dir}")

    rows = _inventory(fits_paths)
    _write_csv(output / "header_inventory.csv", rows)

    bias_paths = _paths_matching(rows, session_dir, IMAGETYP="BIAS")
    dark_paths = [
        str(session_dir / row["filename"])
        for row in rows
        if row.get("IMAGETYP") == "DARK"
        and math.isclose(float(row.get("EXPTIME") or -1), 0.05, abs_tol=1e-5)
    ]
    if len(bias_paths) < 2 or len(dark_paths) < 2:
        raise ValueError("Need at least two bias and two matched 0.05 s dark frames")

    master_bias = ct.master_bias(bias_paths, method="median", chunk_rows=100)
    master_dark = ct.master_dark(
        dark_paths, master_bias, method="median", chunk_rows=100
    )
    rn_map, temporal_std = ct.read_noise_map_from_paths(
        bias_paths, chunk_rows=100
    )
    bad_mask = (
        _outlier_mask(master_bias)
        | _outlier_mask(master_dark)
        | _outlier_mask(rn_map)
        | _outlier_mask(temporal_std)
    )

    _write_image(output / "master_bias.fits", master_bias, "Median master bias", "ADU")
    _write_image(
        output / "master_dark_0.05s.fits", master_dark,
        "Median 0.05 s dark minus master bias", "ADU",
    )
    _write_image(output / "read_noise_map.fits", rn_map, "Frame-difference read noise", "ADU")
    _write_image(
        output / "bad_pixel_mask.fits", bad_mask.astype(np.uint8),
        "Conservative commissioning bad-pixel mask (1=bad)", "boolean",
    )

    sequence_groups: dict[tuple[str, str, str], list[dict[str, Any]]] = defaultdict(list)
    for row in rows:
        if row.get("POLSEQ"):
            sequence_groups[(str(row.get("OBJECT")), str(row.get("POLSEQ")),
                             str(row.get("FILTER")))].append(row)
    sequence_rows: list[dict[str, Any]] = []
    for (obj, seq, filt), members in sorted(sequence_groups.items()):
        sequence_rows.append({
            "object": obj,
            "polseq": seq,
            "filter": filt,
            "n_frames": len(members),
            "n_angles": len({float(m["HWPANG"]) for m in members}),
            "angles_deg": ";".join(
                f"{value:g}" for value in sorted({float(m["HWPANG"]) for m in members})
            ),
            "frames_per_angle": ";".join(
                str(sum(float(m["HWPANG"]) == value for m in members))
                for value in sorted({float(m["HWPANG"]) for m in members})
            ),
            "date_obs_valid": sum(bool(m["date_obs_valid_2026"]) for m in members),
            "date_obs_invalid": sum(not bool(m["date_obs_valid_2026"]) for m in members),
        })
    _write_csv(output / "sequence_inventory.csv", sequence_rows)

    representative = _representative_paths(rows, session_dir)
    frame_metrics: list[dict[str, Any]] = []
    overview_by_sequence: dict[str, tuple[str, np.ndarray]] = {}
    for path in representative:
        hdr = fits.getheader(path, ignore_missing_end=True)
        corrected = ct.load_frame(str(path)) - master_bias - master_dark
        values = corrected[~bad_mask]
        peaks, _smooth, _expanded_bad = _candidate_peaks(corrected, bad_mask)
        pairs = _nominal_vertical_pairs(peaks)
        frame_metrics.append({
            "filename": path.name,
            "polseq": hdr.get("POLSEQ"),
            "hwp_angle_deg": float(hdr.get("HWPANG")),
            **{f"corrected_{key}_adu": value for key, value in _robust(values).items()},
            "n_smoothed_peaks_gt8sigma": len(peaks),
            "n_nominal_60px_vertical_pairs": len(pairs),
            "brightest_peak_snr": peaks[0]["smooth_snr"] if peaks else None,
            "best_pair_minimum_snr": pairs[0]["minimum_snr"] if pairs else None,
        })
        seq = str(hdr.get("POLSEQ"))
        overview_by_sequence.setdefault(seq, (seq, corrected))
    _write_csv(output / "representative_frame_metrics.csv", frame_metrics)
    if len(overview_by_sequence) >= 4:
        _plot_representatives(
            output, list(overview_by_sequence.values())[:4], bad_mask
        )

    superflat_metrics = _superflat_roi_metrics(
        rows, session_dir, master_bias, master_dark, bad_mask
    )
    _write_csv(output / "superflat_roi_metrics.csv", superflat_metrics)

    valid_dates = sum(bool(row["date_obs_valid_2026"]) for row in rows)
    light_rows = [row for row in rows if row.get("IMAGETYP") == "LIGHT"]
    temperatures = [
        float(row.get("DET-TEMP", row.get("CCD-TEMP")))
        for row in rows
        if row.get("DET-TEMP") is not None or row.get("CCD-TEMP") is not None
    ]
    metrics: dict[str, Any] = {
        "session_directory": str(session_dir),
        "n_fits": len(rows),
        "frame_types": {
            kind: sum(row.get("IMAGETYP") == kind for row in rows)
            for kind in sorted({str(row.get("IMAGETYP")) for row in rows})
        },
        "n_valid_2026_date_obs": valid_dates,
        "n_invalid_or_missing_date_obs": len(rows) - valid_dates,
        "n_time_source_present": sum(bool(row.get("TIME-SRC")) for row in rows),
        "n_light_frames": len(light_rows),
        "n_light_frames_missing_instrot": sum(row.get("INSTROT") is None for row in light_rows),
        "n_light_frames_missing_pointing": sum(
            row.get("RA") is None or row.get("DEC") is None for row in light_rows
        ),
        "ccd_temperature_c": {
            "minimum": min(temperatures),
            "median": float(np.median(temperatures)),
            "maximum": max(temperatures),
        },
        "master_bias_adu": _robust(master_bias),
        "master_dark_0.05s_adu": _robust(master_dark),
        "read_noise_map_adu": _robust(rn_map),
        "temporal_std_map_adu": _robust(temporal_std),
        "bad_pixel_count": int(np.count_nonzero(bad_mask)),
        "bad_pixel_fraction": float(np.mean(bad_mask)),
        "sequences": sequence_rows,
        "representative_frames": frame_metrics,
        "superflat_roi": superflat_metrics,
    }
    with (output / "metrics.json").open("w", encoding="utf-8") as handle:
        json.dump(metrics, handle, indent=2, default=_jsonable)
        handle.write("\n")
    return metrics


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "session_dir", nargs="?", type=Path, default=Path("FITSDATA/20260709")
    )
    parser.add_argument(
        "--output", type=Path,
        default=Path("generated/salvage_first_light_20260709"),
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    metrics = analyze(args.session_dir, args.output)
    print(json.dumps({
        "output": str(args.output),
        "n_fits": metrics["n_fits"],
        "bad_pixel_fraction": metrics["bad_pixel_fraction"],
        "invalid_date_obs": metrics["n_invalid_or_missing_date_obs"],
    }, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
